intranet/apps/api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from apps.api import views as v
from rest_framework_swagger.views import get_swagger_view

app_name = 'module_api'

whost = None
if settings.DEBUG == False:
    whost = settings.PREFIX_URL

schema_view = get_swagger_view(
    title="API Interface for SKBerge Peru",
    url=whost,
)

urlpatterns = [
    url(r'^$', schema_view, name='root'),
    url(
        r'^metas/',
        include([
            url(r'^obtener_ventas/$', v.APIGetVentas.as_view(),
                name='sql_obtener_ventas'),
            url(r'^actualizar_marcas/?$', v.APIUpdateMarcas.as_view(),
                name='actualizar_marcas'),
            url(r'^actualizar_concesionarios/?$', v.APIUpdateConcesionarios.as_view(),
                name='actualizar_concesionarios'),
            url(r'^enviar_emails/?$', v.APISendEmailMetas.as_view(),
                name='enviar_emails'),
            url(r'^obtener_empleados/$', v.APIGetEmpleados.as_view(),
                name='sql_obtener_empleados'),
            url(r'^actualizar_empleados/?$', v.APIUpdateEmpleados.as_view(),
                name='actualizar_empleados'),
            url(r'^actualizar_sucursales/?$', v.APIUpdateSucursales.as_view(),
                name='actualizar_sucursales'),
            url(r'^actualizar_areas/?$', v.APIUpdateArea.as_view(),
                name='actualizar_areas'),
            url(r'^actualizar_puestos/?$', v.APIUpdatePuestos.as_view(),
                name='actualizar_puestos'),
        ]),
    ),
    url(
        r'^metas_intranet/',
        include([
            url(r'^metas_obtener_jefes/?$',
                v.APIGetJefes.as_view(),
                name='metas_obtener_jefes'),
            url(r'^metas_obtener_empleados/?$',
                v.APIMetasEmpleados.as_view(),
                name='metas_obtener_empleados'),
            url(r'^metas_obtener_marcas/?$',
                v.APIGetMarcas.as_view(),
                name='metas_obtener_marcas'),
            url(r'^metas_obtener_estados/?$',
                v.APIGetEstados.as_view(),
                name='metas_obtener_estados'),
        ]),
    ),
    url(
        r'^catalogos_intranet/',
        include([
            url(r'^catalogos_obtener_plantas/?$',
                v.APIGetPlantas.as_view(),
                name='catalogos_obtener_plantas'),
            url(r'^catalogos_obtener_salas/?$',
                v.APIGetSalas.as_view(),
                name='catalogos_obtener_salas'),
            url(r'^catalogos_obtener_usuario_permisos/?$',
                v.APIGetUsuarioPermisos.as_view(),
                name='catalogos_obtener_usuario_permisos'),
            url(r'^catalogos_obtener_perfil_permisos/?$',
                v.APIGetPerfilPermisos.as_view(),
                name='catalogos_obtener_perfil_permisos'),
        ]),
    ),
    url(
        r'^reservas_intranet/',
        include([
            url(r'^reserva_obtener_recurrencia/?$',
                v.APIGetRecurrence.as_view(),
                name='reserva_obtener_recurrencia'),
            url(r'^reserva_obtener_weekdays/?$',
                v.APIGetRecurrenceWeekDays.as_view(),
                name='reserva_obtener_weekdays'),
        ]),
    ),
]

intranet/apps/reservas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from apps.reservas import views as v

app_name = 'module_reservas'

urlpatterns = [
    url(r'^reservas_salas/$', v.ViewReservasSalas.as_view(), name='reservas_salas'),
    url(r'^reservas_feriados/$', v.ViewReservasFeriados.as_view(),
        name='reservas_feriados'),
    url(r'^reservas_calendario/$',
        v.ViewReservasCalendario.as_view(), name='reservas_calendario'),
    url(r'^reservas_programacion/(?P<idsala>\d{1,2})/$',
        v.ViewReservasProgramacion.as_view(),
        name='reservas_programacion_sala'),
    url(r'^reservas_programacion/$',
        v.ViewReservasProgramacion.as_view(), name='reservas_programacion'),
    url(r'^reservas_alerts/(?P<reservaid>\d+)/?$',
        v.ReservasAlerts.as_view(), name='reservas_alerts'),
    url(r'^reservas_alerts/(?P<confirmationid>[a-zA-Z]+)/(?P<hashid>[a-zA-Z-0-9]+)/?$',
        v.ReservasAlerts.as_view(), name='reservas_alerts_confirmation'),
    # url(r'^reservas_generar_calendario/$',
    # v.ViewGenerateCalendar.as_view(), name='reservas_generar_calendario'),
]

intranet/intranet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from intranet import views as v

handler404 = 'intranet.views.handler404'
handler500 = 'intranet.views.handler500'

urlpatterns = [
    url(r'^admin/?', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace='login'),),
    url(r'^main/', include('apps.main.urls', namespace='main'),),
    url(r'^api/v1/', include('apps.api.urls', namespace='apiv1'),),
    url(r'^metas/', include('apps.metas.urls', namespace='metas'),),
    url(r'^mail/', include('apps.mail.urls', namespace='mail'),),
    url(r'^reservas/', include('apps.reservas.urls', namespace='reservas'),),
    url(r'^nofound/', v.handler404, name="nofound"),
    url(r'^grants/', include('apps.grants.urls', namespace='grants'),),
    url(r'^$', RedirectView.as_view(url='login/', permanent=False)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

intranet/apps/reservas/views.py
from django.shortcuts import render
from django.views import View
from rest_framework.response import Response
from rest_framework.views import APIView
from django.http import (
    JsonResponse,
    Http404,
)
from apps.metas import (
    models as mdlmetas
)
from apps.catalogos import (
    models as mdlcat,
    serializers as srlzcat,
)
from apps.reservas import (
    models as mdl,
    serializers as srlz,
)
from django.db.models import (
    Value, Case, When, CharField, Q, F, Count,
    Prefetch, IntegerField, CharField,
)

from apps.connections.config import (
    MYSQLConnection,
)
from apps.common.utils import Validators
import json

# Create your views here.

from django.utils.decorators import method_decorator as md
from django.contrib.auth.decorators import (
    login_required,
    permission_required as perm,
)
from django.core.exceptions import PermissionDenied
from apps.reservas.utils import (
    getScheduleList, getScheduleListBySala,
    sendMailBookingConfirmation,
    mailBookingGetReserva,
    getTimeInRange,
    registerRecurrenceEvents,
)
from datetime import datetime, timedelta
import time

from apps.mail.views import ICalendarGenerator, SendMailer

# added at 2020.01.18
import requests
import msal

DEFAULT_FORBIDDEN_PAGE = '/login/forbidden'


@md(login_required, name='dispatch')
class ViewReservasSalas(View):
    template_name = 'reservas/reservas_salas.html'
    template_header = 'SKBerge | Salas de Reservación'
    template_title = 'Salas de Reservación'
    defaultResponse = {
        "ok": 1,
        "result": 'Process has been processed successfuly.',
        "status": 200,
    }

    def dispatch(self, *args, **kwargs):
        return super(ViewReservasSalas, self).dispatch(*args, **kwargs)

    @md(perm('catalogos.add_sala', login_url=DEFAULT_FORBIDDEN_PAGE,),)
    def get(self, request):
        wresponse = self.defaultResponse.copy()
        header = self.template_header
        title = self.template_title
        return render(request, self.template_name, locals())

    @md(perm('catalogos.add_sala', raise_exception=True),)
    def post(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            if not request.is_ajax():
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            if wdata.get("wtype"):
                wtype = wdata.get("wtype")
                if wtype == "get_reservas_sala":
                    return self.getSalasSearch(request)
                if wtype == "save_information":
                    return self.saveInformation(request)
                if wtype == "update_reserva_sala":
                    return self.updateSalas(request)
                if wtype == "remove_reserva_sala":
                    return self.removeSala(request)
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if type(e) is PermissionDenied:
                wresponse['status'], wresponse[
                    'result'] = 403, 'Permission Denied'
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @md(perm('catalogos.add_sala', raise_exception=True),)
    def getSalasSearch(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            # connection = MYSQLConnection()
            wdata = json.loads(request.body.decode("utf8"))
            wfilters = {}
            wsala = wdata.get('sala') or ''
            wplanta = wdata.get('planta') or ''
            westado = wdata.get('estado') or ''

            if wsala != '':
                wfilters['descripcion__icontains'] = wsala
            if westado != '':
                wfilters['estado'] = mdlmetas.Estados.objects.get(
                    id=int(westado))
            if wplanta != '':
                wfilters['planta'] = mdlcat.Planta.objects.get(
                    id=int(wplanta))

            wqueryset = mdlcat.Sala.objects.filter(**wfilters) \
                .select_related("estado") \
                .select_related("username") \
                .select_related("planta") \
                .order_by("descripcion").distinct()
            # print(str(wqueryset.query))
            wfields = [
                "id", "fhregistro", "fhmodificacion",
                "descripcion", "limite_participantes",
                "estado", "planta", "username", "username_modif",
                "fecha_vigencia", "hora_inicio", "hora_final",
            ]
            woutcome = srlzcat.SalaSerializer(
                wqueryset,
                fields=wfields,
                many=True,
            ).data
            wresponse['result'] = woutcome
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @md(perm('catalogos.add_sala', raise_exception=True),)
    def saveInformation(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            wdescription = wdata.get("descripcion") or ''
            if len(wdescription) == 0:
                raise ValueError('Error, descripcion no puede ser null.')
            westado = wdata.get("estado")
            wplanta = wdata.get("planta")
            wcapacidad = wdata.get("capacidad") or 1
            whora_inicio = wdata.get("hora_inicio") or None
            whora_final = wdata.get("hora_final") or None
            wfecha_vigencia = wdata.get("fecha_vigencia") or None
            if not wfecha_vigencia is None:
                wfecha_vigencia, wstatus = Validators.isDate(
                    wfecha_vigencia, "%Y-%m-%d")
                if not wstatus:
                    raise ValueError('Error, Fecha Vigencia invalida.')

            objEstado = mdlmetas.Estados.objects.get(id=int(westado))
            objPlanta = mdlcat.Planta.objects.get(id=int(wplanta))
            wparameters = {
                "descripcion": wdescription.strip().upper(),
                "planta": objPlanta,
                "estado": objEstado,
                "limite_participantes": wcapacidad,
                "fecha_vigencia": wfecha_vigencia,
                "hora_inicio": whora_inicio,
                "hora_final": whora_final,
                "username": request.user,
            }
            objSala = mdlcat.Sala(**wparameters)
            objSala.save()
            wresponse['result'] = {
                "id": objSala.pk,
                "message": "Sala de Reserva procesada satisfactoriamente.",
            }
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @md(perm('catalogos.change_sala', raise_exception=True),)
    def updateSalas(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            widsala = wdata.get("id") or 0
            objSala = mdlcat.Sala.objects.get(id=int(widsala))
            wdescription = wdata.get("descripcion") or ''
            wcapacidad = wdata.get("capacidad") or 1
            whora_inicio = wdata.get("hora_inicio") or None
            whora_final = wdata.get("hora_final") or None
            if objSala == None:
                raise ValueError('Error, sala especificada no existe.')
            if len(wdescription) == 0:
                raise ValueError('Error, descripcion no puede ser null.')
            wfecha_vigencia = wdata.get("fecha_vigencia") or None
            if not wfecha_vigencia is None:
                wfecha_vigencia, wstatus = Validators.isDate(
                    wfecha_vigencia, "%Y-%m-%d")
                if not wstatus:
                    raise ValueError('Error, fecha vigencia invalida.')

            widestado = wdata.get("estado") or 0
            widplanta = wdata.get("planta") or 0
            objEstado = mdlmetas.Estados.objects.get(id=int(widestado))
            objPlanta = mdlcat.Planta.objects.get(id=int(widplanta))

            objSala.estado = objEstado
            objSala.planta = objPlanta
            objSala.descripcion = wdescription.strip().upper()
            objSala.limite_participantes = wcapacidad
            objSala.fecha_vigencia = wfecha_vigencia
            objSala.hora_inicio = whora_inicio
            objSala.hora_final = whora_final
            objSala.username_modif = request.user
            objSala.save()
            wresponse['result'] = {
                "id": objSala.pk,
                "message": "Cambios fueron actualizados satisfactoriamente",
            }
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @md(perm('catalogos.delete_sala', raise_exception=True),)
    def removeSala(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            widsala = wdata.get("item").get("id") or 0

            wfrom = datetime.now() - timedelta(days=7)
            wto = wfrom + timedelta(days=60)

intranet/templates/reservas/reservas_calendario.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	
	 <link rel="stylesheet" href="{% static '/css/reservas_calendario.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerTabs"  id="vTabs">
		<p>
			<router-link to="/"> Reservaciones</router-link>
			<!-- <router-link 
				to="/reserva"> 
				Formulario 
			</router-link> -->
		</p>
		<router-view 
			@change-page="onChangePage" 
			@close-dialog="onCloseDialog"
			@refresh-employees="getEmpleados"
			@get-salas-allowed="getSalasByGrants"
			>
		</router-view>
	</div>

	<div id="container-requests">
		<div class="layerData" id="vContainer" >
			<div class="row layerFields">
				<form data-toggle="validator" role="form">
					<div class="form-row">
						<div class="form-group col-12 col-sm-6 col-md-4 col-lg-3">
							<label class="form-label"
								 for="">Sala / Motivo</label>
							<input 
								type="text" 
								class="form-control input-lg"  
								v-model = "descripcion"
								name="descripcion"
								autocomplete="off" 
								>
						</div>
						<div class="form-group col-12 col-sm-6 col-md-4 col-lg-3">
							<label class="form-label"
								 for="">Fecha Desde</label>
							<el-date-picker
							      v-model="fecha_desde"
							      type="date"
							      placeholder="Seleccione Fecha"
							      format="dd/MM/yyyy"
								  value-format="yyyy-MM-dd"
								  name="fecha_desde"
							      >
						    </el-date-picker>
						    <div v-if="hasError('fecha_desde')"
						    	class="alert alert-danger" 
						    	role="alert">Completar el campo</div>
						</div>
						<div class="form-group col-12 col-sm-6 col-md-4 col-lg-3">
							<label class="form-label"
								 for="">Fecha Hasta</label>
							<el-date-picker
							      v-model="fecha_hasta"
							      type="date"
							      placeholder="Seleccione Fecha"
							      format="dd/MM/yyyy"
								  value-format="yyyy-MM-dd"
								  name="fecha_hasta"
							      >
						    </el-date-picker>
						      <div v-if="hasError('fecha_hasta')"
						    	class="alert alert-danger" 
						    	role="alert">Completar el campo</div>
						</div>
						<div class="form-group col-12 col-sm-6 col-md-4 col-lg-3">
							<label
								class="form-label">Estado</label>
							<el-select v-model="estado" 
								placeholder="Seleccione"
								
								filterable
								clearable>
							    <el-option
							      v-for="item in list.list_estados"
							      :key="item.id"
							      :label="item.value"
							      :value="item.id">
							    </el-option>
							</el-select>
						</div>
					</div>
					<div class="form-row">
						<div class="col-12 col-sm-6 col-md-4 col-lg-2">
							<button class="btn btn-sm btn-primary btn-block" 
								@click.prevent="handleSearch">
								<i class="fas fa-search"></i>
								Buscar
							</button>	
						</div>
						<div class="col-12 col-sm-6 col-md-4 col-lg-2">
							<button class="btn btn-sm btn-warning btn-block" 
								@click.prevent="handleCleanFields">
								<i class="fas fa-backspace"></i>
								Limpiar Campos
							</button>
						</div>
						<div class="col-12 col-sm-6 col-md-4 col-lg-2">
							<button class="btn btn-sm btn-success btn-block" 
									@click.prevent="handleNew">
									<i class="fas fa-plus-circle"></i>
									Agregar Reserva
							</button>
						</div>
						<div class="col-12 col-sm-6 col-md-4 col-lg-2">
							<button class="btn btn-sm btn-danger btn-block" 
									@click.prevent="anularReserva">
									<i class="fas fa-ban"></i>
									Anular Reserva
							</button>
						</div>
					</div>
				</form>				
			</div>
			<div class="layerTable">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>
								<el-checkbox 
								 	v-model="check_all" 
								 	border
								 	title="Seleccionar todos"
								 	size="small"
								 	>
								 </el-checkbox>
							</th>
							<th></th>
							<th>Fecha</th>
							<th>Horario</th>
							<th>Sala</th>
							<th>Solicitante</th>
							<th>Motivo</th>
							<th>Estado</th>
							<th>Fh. Ingreso</th>
							<th>Fh. Modif.</th>
							<th>Usu. Modif</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="item in lst_items"
							v-bind:class="{'check-edit':item.check}">
							<td>
								<el-checkbox 
								 	v-model="item.check" 
								 	:border="true"
									size="small"
								 	>
								 </el-checkbox>
							</td>
							<td>
								{% comment %}
									<button type="button" 
										@click.remove="anularReserva(item)"
										class="btn btn-danger btn-sm"
										title="Cancelar">
										<i class="fas fa-minus-circle"></i>
									</button>
								{% endcomment %}
								<button type="button" 
									@click.remove="modifyReserva(item)"
									class="btn btn-info btn-sm"
									title="Modificar">
									<i class="fas fa-pen-square"></i>
								</button>
							</td>
							<td>
								${item.fecha_evento| format("DD/MM/Y")}
							</td>
							<td>
								${item.hora_inicio} a ${item.hora_final}
							</td>
							<td > 
								${item.sala.descripcion}
							</td>
							<td > 
								${item.empleado.nombres} ${item.empleado.apellidos}
							</td>
							<td >
								${item.motivo} 
							</td>
							<td > 
								${item.estado.descripcion}
							</td>
							<td>
								${item.fhregistro| format("DD/MM/Y HH:MM:ss")}
							</td>
							<td>
								${item.fhmodificacion| format("DD/MM/Y HH:MM:ss")}
							</td>
							<td>
								${item.username_modif ? item.username_modif:''}
							</td>
							<td>
								<i class="fas fa-redo-alt" v-if="item.recurrence==1" title="Evento recurrente">
								</i>
							</td>
						</tr>
						<tr v-if="lst_items.length==0">
							<td colspan="12">
								No se encontraron resultados
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="summary">
				<div>
					<span>Total Registros :</span>
					<label>${totales.filas}</label>
				</div>
			</div>
		</div>
	</div>
	<div id="container-form">
		<div id="vItem">
			{% include 'reservas/forms/form_reservas.html' %}
			{% include 'reservas/forms/salas_disponibles.html' %}
			{% include 'reservas/forms/form_external_member.html' %}
		</div>
	</div>

{% endblock %}

{% block additionaljs %}
	<script src="{% static '/js/unpkg.com/vue-router@3.0.1/dist/vue-router.min.js' %}"></script>
	
	<script type="text/javascript">
		
		const URI_HOME = window.location.pathname ;
		const URI_ESTADO = "{% url 'apiv1:metas_obtener_estados' %}";
		const URI_SALAS = "{% url 'apiv1:catalogos_obtener_salas' %}";
		const URI_PLANTAS = "{% url 'apiv1:catalogos_obtener_plantas' %}";
		const URI_EMPLEADOS = "{% url 'apiv1:metas_obtener_empleados' %}";
		
		// added at 2020.02.01
		const URI_RECURRENCE = "{% url 'apiv1:reserva_obtener_recurrencia'%}" ;
		const URI_WEEKDAYS = "{% url 'apiv1:reserva_obtener_weekdays'%}" ;

		{% if user.empleado_intranet_set.id  %}
			const uidemployer = {{user.empleado_intranet_set.id}} ;
		{%else%}
			const uidemployer = 0 ;
		{%endif%}
	</script>
	<script src="{% static '/js/reservas_calendario.js' %}"></script>
{% endblock %}

intranet/templates/reservas/reservas_feriados.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	 
	 <link rel="stylesheet" href="{% static '/css/reservas_feriados.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerData" id="vContainer">
		<div class="layerFields">
			<div class="col-sm-12 col-md-12 col-lg-6">
				<div class="form-group">
					<label class="form-label col-3 col-sm-3 col-lg-3" for="">Fecha</label>
					<input type="text" 
							class="form-control input-lg" 
							v-model="fecha" >
				</div>	
			</div>
			<div class="col-sm-12 col-md-12 col-lg-6">
				<button class="btn btn-primary" 
					@click.prevent="getSearch"
					title="Buscar">
					<i class="fas fa-search"></i>
					Buscar
				</button>
				<button class="btn btn-success" 
					@click.prevent="newItem"
					title="Nuevo">
					<i class="fas fa-plus-circle"></i>
					Nuevo
				</button>
			</div>
		</div>
		<div class="layerTable">
			<table class="table table-hover">
				<thead>
					<tr>
						<th></th>
						<th>Fecha</th>
						<th>Descripción</th>
						<th>Estado</th>
						<th>Fh. Ingreso</th>
						<th>Fh. Modif.</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="item in lst_items">
						<td>
							<button type="button" 
								@click.remove="removeMeta(item)"
								class="btn btn-danger btn-sm"
								title="Eliminar">
								<i class="fas fa-minus-circle"></i>
							</button>
							<button type="button" 
								@click.remove="modifyMeta(item)"
								class="btn btn-info btn-sm"
								title="Modificar">
								<i class="fas fa-pen-square"></i>
							</button>
						</td>
						<td > 
							${item.fecha|format("DD/MM/Y")}
						</td>
						<td > ${item.descripcion}</td>
						<td > ${item.estado.descripcion}</td>
						<td>
							${item.fhregistro| format("DD/MM/Y HH:MM:ss")}
						</td>
						<td>
							${item.fhmodificacion| format("DD/MM/Y HH:MM:ss")}
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="summary">
			<div>
				<span>Total Activos :</span>
				<label>${totales.habilitados}</label>
			</div>
			<div>
				<span>Total No Activos :</span>
				<label>${totales.nohabilitados}</label>
			</div>
			<div>
				<span>Total Registros :</span>
				<label>${totales.filas}</label>
			</div>
		</div>
	</div>
	<div id="vModal" v-bind:class="{locked:style_locked}">
		{% include 'reservas/forms/form_feriados.html' %}
	</div>

{% endblock %}

{% block additionaljs %}
	
	<script type="text/javascript">
		const URI_HOME = window.location.pathname ;
		const URI_ESTADO = "{% url 'apiv1:metas_obtener_estados' %}";
	</script>
	<script src="{% static '/js/reservas_feriados.js' %}"></script>
{% endblock %}