intranet/apps/api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from apps.api import views as v
from rest_framework_swagger.views import get_swagger_view

app_name = 'module_api'

whost = None
if settings.DEBUG == False:
    whost = settings.PREFIX_URL

schema_view = get_swagger_view(
    title="API Interface for SKBerge Peru",
    url=whost,
)

urlpatterns = [
    url(r'^$', schema_view, name='root'),
    url(
        r'^metas/',
        include([
            url(r'^obtener_ventas/$', v.APIGetVentas.as_view(),
                name='sql_obtener_ventas'),
            url(r'^actualizar_marcas/?$', v.APIUpdateMarcas.as_view(),
                name='actualizar_marcas'),
            url(r'^actualizar_concesionarios/?$', v.APIUpdateConcesionarios.as_view(),
                name='actualizar_concesionarios'),
            url(r'^enviar_emails/?$', v.APISendEmailMetas.as_view(),
                name='enviar_emails'),
            url(r'^obtener_empleados/$', v.APIGetEmpleados.as_view(),
                name='sql_obtener_empleados'),
            url(r'^actualizar_empleados/?$', v.APIUpdateEmpleados.as_view(),
                name='actualizar_empleados'),
            url(r'^actualizar_sucursales/?$', v.APIUpdateSucursales.as_view(),
                name='actualizar_sucursales'),
            url(r'^actualizar_areas/?$', v.APIUpdateArea.as_view(),
                name='actualizar_areas'),
            url(r'^actualizar_puestos/?$', v.APIUpdatePuestos.as_view(),
                name='actualizar_puestos'),
        ]),
    ),
    url(
        r'^metas_intranet/',
        include([
            url(r'^metas_obtener_jefes/?$',
                v.APIGetJefes.as_view(),
                name='metas_obtener_jefes'),
            url(r'^metas_obtener_empleados/?$',
                v.APIMetasEmpleados.as_view(),
                name='metas_obtener_empleados'),
            url(r'^metas_obtener_marcas/?$',
                v.APIGetMarcas.as_view(),
                name='metas_obtener_marcas'),
            url(r'^metas_obtener_estados/?$',
                v.APIGetEstados.as_view(),
                name='metas_obtener_estados'),
        ]),
    ),
    url(
        r'^catalogos_intranet/',
        include([
            url(r'^catalogos_obtener_plantas/?$',
                v.APIGetPlantas.as_view(),
                name='catalogos_obtener_plantas'),
            url(r'^catalogos_obtener_salas/?$',
                v.APIGetSalas.as_view(),
                name='catalogos_obtener_salas'),
            url(r'^catalogos_obtener_usuario_permisos/?$',
                v.APIGetUsuarioPermisos.as_view(),
                name='catalogos_obtener_usuario_permisos'),
            url(r'^catalogos_obtener_perfil_permisos/?$',
                v.APIGetPerfilPermisos.as_view(),
                name='catalogos_obtener_perfil_permisos'),
        ]),
    ),
    url(
        r'^reservas_intranet/',
        include([
            url(r'^reserva_obtener_recurrencia/?$',
                v.APIGetRecurrence.as_view(),
                name='reserva_obtener_recurrencia'),
            url(r'^reserva_obtener_weekdays/?$',
                v.APIGetRecurrenceWeekDays.as_view(),
                name='reserva_obtener_weekdays'),
        ]),
    ),
]

intranet/apps/metas/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from apps.metas import views as v

app_name = 'module_metas'

urlpatterns = [
    url(r'^meta_jefe/$', v.ViewMetaJefe.as_view(), name='meta_jefe'),
    url(r'^meta_marca/$', v.ViewMetaMarca.as_view(), name='meta_marca'),
    url(r'^meta_concesionario/$',
        v.ViewMetaAsignaConcesionario.as_view(), name='meta_asigna_concesionario'),
]

intranet/intranet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from intranet import views as v

handler404 = 'intranet.views.handler404'
handler500 = 'intranet.views.handler500'

urlpatterns = [
    url(r'^admin/?', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace='login'),),
    url(r'^main/', include('apps.main.urls', namespace='main'),),
    url(r'^api/v1/', include('apps.api.urls', namespace='apiv1'),),
    url(r'^metas/', include('apps.metas.urls', namespace='metas'),),
    url(r'^mail/', include('apps.mail.urls', namespace='mail'),),
    url(r'^reservas/', include('apps.reservas.urls', namespace='reservas'),),
    url(r'^nofound/', v.handler404, name="nofound"),
    url(r'^grants/', include('apps.grants.urls', namespace='grants'),),
    url(r'^$', RedirectView.as_view(url='login/', permanent=False)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

intranet/apps/metas/views.py
from django.shortcuts import render
from django.views import View
from rest_framework.response import Response
from rest_framework.views import APIView
from django.http import JsonResponse
from apps.metas import (
    models as mdl,
    serializers as srlz,
    querys as q
)
from django.db.models import Value, Case, When, CharField
from apps.connections.config import (
    MYSQLConnection,
)
import json

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import (
    login_required,
    permission_required,
)
from django.core.exceptions import PermissionDenied

from apps.api.querys import (
    cmd_metas_obtener_ventas,
)

# Create your views here.

DEFAULT_FORBIDDEN_PAGE = '/login/forbidden'


@method_decorator(login_required, name='dispatch')
class ViewMetaAsignaConcesionario(View):
    template_name = 'metas/meta_asigna_concesionario.html'
    template_header = 'SKBerge | Asignación Concesionarios'
    template_title = 'Asignación de Concesionarios'
    defaultResponse = {
        "ok": 1,
        "result": 'Process has been processed successfuly.',
        "status": 200,
    }

    def dispatch(self, *args, **kwargs):
        return super(ViewMetaAsignaConcesionario, self).dispatch(*args, **kwargs)

    @method_decorator(permission_required(
        'metas.add_marcajefeconcesionario', login_url=DEFAULT_FORBIDDEN_PAGE,),)
    def get(self, request):
        wresponse = self.defaultResponse.copy()
        header = self.template_header
        title = self.template_title
        return render(request, self.template_name, locals())

    @method_decorator(permission_required(
        'metas.add_marcajefeconcesionario', raise_exception=True),)
    def post(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            if not request.is_ajax():
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            if wdata.get("wtype"):
                wtype = wdata.get("wtype")
                if wtype == "save_information":
                    return self.saveInformation(request)
                if wtype == "get_metas_concesionarios":
                    return self.getMetasConcesionarios(request)
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if type(e) is PermissionDenied:
                wresponse['status'], wresponse[
                    'result'] = 403, 'Permission Denied'
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @method_decorator(permission_required('metas.add_marcajefeconcesionario', raise_exception=True),)
    def getMetasConcesionarios(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            connection = MYSQLConnection()
            wdata = json.loads(request.body.decode("utf8"))
            wfilters = {}
            wjefe = wdata.get('jefe') or 'null'
            wmarca = wdata.get('marca') or 'null'
            wcmd = q.cmd_listar_concesionarios.format(wmarca, wjefe)
            werror, wresult = connection.get_query_dict(wcmd)
            if werror:
                raise ValueError(str(werror))
            wresponse['result'] = wresult
            return JsonResponse(wresponse, status=wresponse.get("status"))

            # if wjefe != '':
            #     wfilters['jefe'] = mdl.Empleados.objects.get(id=int(wjefe))
            # if wmarca != '':
            #     wfilters['marca'] = mdl.Marca.objects.get(id=int(wmarca))

            # wqueryset = mdl.Concesionario.objects.values("id", "nombre", "ndoc") \
            #     .annotate(asignado=Case(
            #         When(
            #             marcajefeconcesionario__id__isnull=False,
            #             then=Value("1")),
            #         default=Value("0"),
            #         output_field=CharField(),)
            # ).filter(
            #     marcajefeconcesionario__marca=wfilters.get("marca"),
            #     marcajefeconcesionario__jefe=wfilters.get("jefe")) \
            #     .exclude(estado__id=2).order_by("nombre").distinct()
            # print(str(wqueryset.query))
            # wfields = [
            #     "id", "nombre", "ndoc", "asignado"
            # ]
            # woutcome = srlz.ConcesionarioSerializer(
            #     wqueryset,
            #     many=True,
            #     fields=wfields,
            # ).data
            # wresponse['result'] = woutcome
            # return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    @method_decorator(permission_required('metas.change_marcajefeconcesionario', raise_exception=True),)
    def saveInformation(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            witems = wdata.get("concesionarios")
            wmarca = wdata.get("marca")
            wjefe = wdata.get("jefe")
            objMarca = mdl.Marca.objects.get(id=int(wmarca))
            objEmpleado = mdl.Empleados.objects.get(id=int(wjefe))
            # first remove any existing details
            mdl.MarcaJefeConcesionario.objects.filter(
                marca=objMarca, jefe=objEmpleado
            ).delete()
            # then insert the new items
            for item in witems:
                wconcesionario = int(item.get("id") or 0)
                objAsignacion = mdl.MarcaJefeConcesionario()
                objAsignacion.marca = objMarca
                objAsignacion.concesionario = mdl.Concesionario.objects.get(
                    id=wconcesionario)
                objAsignacion.jefe = objEmpleado
                objAsignacion.username = request.user
                objAsignacion.save()

            wresponse['result'] = {
                "id": "",
                "message": "Asignación de Concesionarios procesada satisfactoriamente.",
            }
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))


@method_decorator(login_required, name='dispatch')
class ViewMetaJefe(View):
    template_name = 'metas/meta_jefe.html'
    template_header = 'SKBerge | Metas por Jefe'
    template_title = 'Metas por Jefe'
    defaultResponse = {
        "ok": 1,
        "result": 'Process has been processed successfuly.',
        "status": 200,
    }

    def dispatch(self, *args, **kwargs):
        return super(ViewMetaJefe, self).dispatch(*args, **kwargs)

    @method_decorator(permission_required('metas.add_metajefe', login_url=DEFAULT_FORBIDDEN_PAGE,),)
    def get(self, request):
        wresponse = self.defaultResponse.copy()
        header = self.template_header
        title = self.template_title
        return render(request, self.template_name, locals())

    @method_decorator(permission_required('metas.add_metajefe', raise_exception=True),)
    def post(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            if not request.is_ajax():
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            if wdata.get("wtype"):
                wtype = wdata.get("wtype")
                if wtype == "save_information":
                    return self.saveInformation(request)
                if wtype == "get_metas_jefe":
                    return self.getMetasJefe(request)
                if wtype == "remove_meta_jefe":
                    return self.removeMeta(request)
                if wtype == "update_meta_jefe":
                    return self.updateMeta(request)
                if wtype == "get_report_jefe":
                    return self.getReportJefe(request)
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if type(e) is PermissionDenied:
                wresponse['status'], wresponse[
                    'result'] = 403, 'Permission Denied'
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            return JsonResponse(wresponse, status=wresponse.get("status"))

    # @method_decorator(permission_required('metas.add_metajefe', raise_exception=True),)
    def getReportJefe(self, request):
        from apps.api.views import APISendEmailMetas
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            wemployee = wdata.get("jefe").get("id")
            wmonth = wdata.get("mes")
            connection = MYSQLConnection()
            wcmd = cmd_metas_obtener_ventas.format(wmonth, wemployee)
            werror, wresult = connection.get_query_dict(wcmd)
            if werror:
                raise ValueError(str(werror))
            print(len(wresult))
            if len(wresult) == 0:
                raise ValueError(str('Error, No se encontraron resultados.'))

            obj = APISendEmailMetas()
            error, wresult = obj.generate_files(wresult, request)
            if error:
                raise ValueError(str(error))
            wresponse["result"] = {

intranet/templates/metas/meta_asigna_concesionario.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	 
	 <link rel="stylesheet" href="{% static '/css/meta_concesionario.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerData" id="vContainer">
		<template>
			<div class="layerFields">
				<div class="row">
					<div class="col-12 col-sm-6 col-md-6 col-lg-4">
						<div class="form-group">
							<label for="">Marca</label>
							<el-select v-model="marca" 
								placeholder="Seleccione"
								
								filterable
								clearable>
							    <el-option
							      v-for="item in list.list_marcas"
							      :key="item.id"
							      :label="item.value"
							      :value="item.id">
							    </el-option>
							</el-select>
						</div>	
					</div>
					<div class="col-12 col-sm-6 col-md-6 col-lg-4">
						<div class="form-group">
							<label for="">Jefe</label>
							<el-select v-model="jefe" 
								placeholder="Seleccione"
								
								filterable
								clearable>
							    <el-option
							      v-for="item in list.list_jefes"
							      :key="item.id"
							      :label="item.value"
							      :value="item.id">
							    </el-option>
							</el-select>
						</div>	
					</div>
				</div>
				<div class="row">
					<div class="col-12 col-sm-6 col-md-3 col-lg-3">
						<button class="btn btn-primary btn-block" 
							@click.prevent="getSearch">
							<i class="fas fa-search"></i>
							Buscar
						</button>
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-3">
						<button class="btn btn-success btn-block" 
							@click.prevent="confirmDialog" :disabled="btn_status">
							<i class="far fa-save"></i>
							Guardar Cambios
						</button>
					</div>
				</div>
			</div>
			
			<div class="layerTable">
				<table class="table table-hover" id="leftside">
					<thead>
						<tr>
							<th style=" width:150px; text-align: center">
								Todos
								<el-checkbox v-model="checked_disable"
									border >
									
								</el-checkbox>
							</th>
							<th>No Asignados</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="item in lst_items_disabled">
							<td style="text-align: center">
								<el-checkbox v-model="item.check"
									border >
								</el-checkbox>
							</td>
							<td v-text="item.nombre"></td>
						</tr>
					</tbody>
				</table>
				<div id="middleside">
					<div class="gb-buttons">
						<button class="btn btn-info" 
							@click.prevent="enableItem">
							Agregar
						</button>
						<button class="btn btn-danger"
							@click.prevent="disableItem">
							Quitar
						</button>
					</div>
				</div>
				<table class="table table-hover" id="rightside">
					<thead>
						<tr>
							<th style=" width:150px; text-align: center">
								Todos
								<el-checkbox v-model="checked_enable" 
									border >
								</el-checkbox>
							</th>
							<th>Asignados</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="item in lst_items_enabled">
							<td style="text-align: center">
								<el-checkbox v-model="item.check"
									border >
								</el-checkbox>
							</td>
							<td v-text="item.nombre"></td>
						</tr>
					</tbody>
				</table>
				<div class="summary">
					<div>
						<span>Total Habilitados</span>
						<label>${totales.habilitados}</label>
					</div>
					<div>
						<span>Total Deshabilitados</span>
						<label>${totales.nohabilitados}</label>
					</div>
					<div>
						<span>Total Registros</span>
						<label>${totales.filas}</label>
					</div>
				</div>
			</div>
		</template>
	</div>

{% endblock %}

{% block additionaljs %}
	
	<script type="text/javascript">
		
		const URI_HOME = window.location.pathname ;
		const URI_JEFES = "{% url 'apiv1:metas_obtener_jefes' %}";
		const URI_MARCAS = "{% url 'apiv1:metas_obtener_marcas' %}";
	</script>
	<script src="{% static '/js/meta_concesionario.js' %}"></script>
{% endblock %}

intranet/templates/metas/meta_jefe.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}

	 <link rel="stylesheet" href="{% static '/css/meta_jefe.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerData" id="vContainer">
		<template>
			<div class="layerFields">
				<div class="row">
					<div class="col-12 col-sm-6 col-md-4 col-lg-3">
						<div class="form-group">
							<label for="">Jefe</label>
							<el-select v-model="jefe" 
								placeholder="Seleccione"
								filterable
								clearable>
							    <el-option
							      v-for="item in list.list_jefes"
							      :key="item.id"
							      :label="item.value"
							      :value="item.id">
							    </el-option>
							</el-select>
						</div>	
					</div>
					<div class="col-12 col-sm-6 col-md-4 col-lg-3">
						<div class="form-group">
							<label for="">Marca</label>
							<el-select v-model="marca" 
								placeholder="Seleccione"
								
								filterable
								clearable>
							    <el-option
							      v-for="item in list.list_marcas"
							      :key="item.id"
							      :label="item.value"
							      :value="item.id">
							    </el-option>
							</el-select>
						</div>	
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<div class="form-group">
							<label for="">Año</label>
							<el-date-picker
							      v-model="anio"
							      type="year"
							      placeholder="Seleccione año"
							      >
						    </el-date-picker>
						</div>
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<div class="form-group">
							<label for="">Mes</label>
							<el-date-picker
							      v-model="mes"
							      type="month"
							      placeholder="Seleccione mes"
							      >
						    </el-date-picker>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<button class="btn btn-primary btn-block" 
							@click.prevent="getSearch">
							<i class="fas fa-search"></i>
							Buscar
						</button>
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<button class="btn btn-success btn-block" 
							@click.prevent="showDialog">
							<i class="fas fa-plus-circle"></i>
							Agregar Meta
						</button>
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<button class="btn btn-warning btn-block" 
							@click.prevent="handleClean">
							<i class="fas fa-backspace"></i>
							Limpiar Campos
						</button>
					</div>
				</div>
			</div>
			
			<div class="layerTable">
				<table class="table table-hover">
					<thead>
						<tr>
							<th></th>
							<th>ID</th>
							<th>Jefe</th>
							<th>Marca</th>
							<th>Meta</th>
							<th>Año</th>
							<th>Mes</th>
							<th>Fh. Ingreso</th>
							<th>Usuario</th>
							<th>Fh. Modif.</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="item in lst_items">
							<td>
								<button type="button" 
									@click.remove="removeMeta(item)"
									class="btn btn-danger"
									title="Eliminar">
									<i class="fas fa-minus-circle"></i>
								</button>
								<button type="button" 
									@click.remove="modifyMeta(item)"
									class="btn btn-info"
									title="Modificar">
									<i class="fas fa-pen-square"></i>
								</button>
								<button type="button" 
									@click.remove="handleExcelReport(item)"
									class="btn btn-success"
									title="Exportar Informe">
									<i class="fas fa-file-excel"></i>
								</button>
							</td>
							<td v-text="item.id"></td>
							<td > 
								${item.jefe ? item.jefe.nombres:''} ${item.jefe ? item.jefe.apellidos:''}
							</td>
							<td >
								${item.marca ? item.marca.nombre:''}
							</td>
							<td v-text="item.meta"></td>
							<td v-text="item.anio"></td>
							<td v-text="item.mes"></td>
							<td>
								${item.fhregistro| format("DD/MM/Y HH:MM:ss")}
							</td>
							<td>
								${item.username ? item.username:''}
							</td>
							<td>
								${item.fhmodificacion| format("DD/MM/Y HH:MM:ss")}
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="summary">
				<div>
					<span>Total Registros :</span>
					<label>${totales.filas}</label>
				</div>
			</div>
		</template>
	</div>
	<div id="vModal">
		<template>
			{% include 'metas/forms/form_jefe.html' %}
		</template>
	</div>

{% endblock %}

{% block additionaljs %}
	
	<script type="text/javascript">
		
		const URI_HOME = window.location.pathname ;
		const URI_JEFES = "{% url 'apiv1:metas_obtener_jefes' %}";
		const URI_MARCAS = "{% url 'apiv1:metas_obtener_marcas' %}";
	</script>
	<script src="{% static '/js/meta_jefe.js' %}"></script>
{% endblock %}

intranet/templates/metas/meta_marca.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}

	 <link rel="stylesheet" href="{% static '/css/meta_marca.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerData" id="vContainer">
		<template>
			<div class="layerFields">
				<div class="row">
					<div class="col-12 col-sm-6 col-md-6 col-lg-4">
						<div class="form-group">
							<label for="">Marca</label>
							<el-select v-model="marca" 
								placeholder="Seleccione"
								filterable
								clearable>
							    <el-option
							      v-for="item in list.list_marcas"
							      :key="item.id"
							      :label="item.value"
							      :value="item.id">
							    </el-option>
							</el-select>
						</div>	
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<div class="form-group">
							<label for="">Año</label>
							<el-date-picker
							      v-model="anio"
							      type="year"
							      placeholder="Seleccione año"
							      >
						    </el-date-picker>
						</div>
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<div class="form-group">
							<label for="">Mes</label>
							<el-date-picker
							      v-model="mes"
							      type="month"
							      placeholder="Seleccione mes"
							      >
						    </el-date-picker>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<button class="btn btn-primary btn-block" 
							@click.prevent="getSearch">
							<i class="fas fa-search"></i>
							Buscar
						</button>
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<button class="btn btn-success btn-block" 
							@click.prevent="showDialog">
							<i class="fas fa-plus-circle"></i>
							Agregar Meta
						</button>
					</div>
					<div class="col-12 col-sm-6 col-md-3 col-lg-2">
						<button class="btn btn-warning btn-block" 
							@click.prevent="handleClean">
							<i class="fas fa-backspace"></i>
							Limpiar Campos
						</button>
					</div>
				</div>
			</div>
			<div class="layerTable">
				<table class="table table-hover">
					<thead>
						<tr>
							<th></th>
							<th>ID</th>
							<th>Marca</th>
							<th>Meta</th>
							<th>Año</th>
							<th>Mes</th>
							<th>Fh. Ingreso</th>
							<th>Usuario</th>
							<th>Fh. Modif.</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="item in lst_items">
							<td>
								<button type="button" 
									@click.remove="removeMeta(item)"
									class="btn btn-danger btn-sm"
									title="Eliminar">
									<i class="fas fa-minus-circle"></i>
								</button>
								<button type="button" 
									@click.remove="modifyMeta(item)"
									class="btn btn-info btn-sm"
									title="Modificar">
									<i class="fas fa-pen-square"></i>
								</button>
							</td>
							<td v-text="item.id"></td>
							<td >
								${item.marca?item.marca.nombre:''}
							</td>
							<td v-text="item.meta"></td>
							<td v-text="item.anio"></td>
							<td v-text="item.mes"></td>
							<td>
								${item.fhregistro| format("DD/MM/Y HH:MM:ss")}
							</td>
							<td>
								${item.username ? item.username:''}
							</td>
							<td>
								${item.fhmodificacion| format("DD/MM/Y HH:MM:ss")}
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="summary">
				<div>
					<span>Total Registros :</span>
					<label>${totales.filas}</label>
				</div>
			</div>
		</template>
	</div>
	<div id="vModal">
		<template>
			{% include 'metas/forms/form_marca.html' %}
		</template>
	</div>

{% endblock %}

{% block additionaljs %}
	
	<script type="text/javascript">
		const URI_HOME = window.location.pathname;
		const URI_MARCAS = "{% url 'apiv1:metas_obtener_marcas' %}";
	</script>
	<script src="{% static '/js/meta_marca.js' %}"></script>
{% endblock %}