intranet/apps/login/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from apps.login import views as v
app_name = 'module_login'

urlpatterns = [
    url(r'^$', v.LoginView.as_view(), name='main'),
    url(r'^refresh/$', v.RefreshView.as_view(), name='refresh'),
    url(r'^logout/$', v.LogoutView.as_view(), name='logout'),
    url(r'^validation/$', v.LoginValidation.as_view(), name='validation'),
    url(r'^change_password/$', v.LoginChangePasswd.as_view(),
        name='change_password'),
    url(r'^additional_information/$', v.LoginAdditionalInfo.as_view(),
        name='additional_information'),
    url(r'^forbidden/$', v.LoginForbidden.as_view(),
        name='forbidden'),
    url(r'^reset_password/(?P<hashid>[a-zA-Z\d]{11})/$',
        v.LoginResetPasswd.as_view(),
        name='reset_password_hash'),
    url(r'^reset_password/$', v.LoginResetPasswd.as_view(),
        name='reset_password'),
    url(r'^update_password/(?P<typeid>[a-zA-Z]{1,10})/?$',
        v.LoginExpirationPassword.as_view(),
        name='update_password_process_type'),
    url(r'^update_password/$', v.LoginExpirationPassword.as_view(),
        name='update_password'),
]

intranet/apps/main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from apps.main import views as v

app_name = 'module_main'

urlpatterns = [
    url(r'^$', v.MainView.as_view(), name='navigator'),
]

intranet/intranet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from intranet import views as v

handler404 = 'intranet.views.handler404'
handler500 = 'intranet.views.handler500'

urlpatterns = [
    url(r'^admin/?', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace='login'),),
    url(r'^main/', include('apps.main.urls', namespace='main'),),
    url(r'^api/v1/', include('apps.api.urls', namespace='apiv1'),),
    url(r'^metas/', include('apps.metas.urls', namespace='metas'),),
    url(r'^mail/', include('apps.mail.urls', namespace='mail'),),
    url(r'^reservas/', include('apps.reservas.urls', namespace='reservas'),),
    url(r'^nofound/', v.handler404, name="nofound"),
    url(r'^grants/', include('apps.grants.urls', namespace='grants'),),
    url(r'^$', RedirectView.as_view(url='login/', permanent=False)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

intranet/apps/main/models.py
from django.db import models

# Create your models here.

intranet/apps/main/views.py
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
# Create your views here.


class MainView(View):

    template_name = 'main/index.html'
    defaultResponse = {
        "ok": 1,
        "status": 200,
        "result": "Request has been processed successfuly.",
    }

    @method_decorator(login_required)
    def get(self, request):
        warguments = {}
        return render(request, self.template_name, **warguments)

intranet/templates/main/index.html
{% extends 'interface/base_main.html' %}
{% load static %}

{% block additionalmeta %}
{% endblock %}	

{% block additionalcss %}
{% endblock %}	

{% block main %}
	<main>
		<header class="top-side">
			{% include 'main/main_header.html' %}
		</header>
		<section class="middle-side">
			{% block middleside %}
				<article class="middle-leftside expand">
					{% include 'main/main_nav.html' %}
				</article>
				<article class="middle-rightside">
					<div class="body-container">
						{% block container %}
						{% endblock %}
					</div>
				</article>
				<article 
					class="middle-rightside-loader">
						<div class="loader"></div>
				</article>
			{% endblock %}
		</section>
		<section class="session-side">
			{% include 'main/main_session.html' %}
		</section>
		<footer class="bottom-side">
			{% now 'Y' as current_year %}
			{% if current_year == year %}
				{{year}}
			{%else%}
				{{year}} - {% now 'Y' %}
			{%endif%}
			{{company}} &copy; Todos los Derechos Reservados
		</footer>
	</main>
{% endblock %}

{% block additionaljs %}
{% endblock %}

intranet/templates/main/main_header.html
<section class="layer-bg"></section>
<section class="layer-sandwich">
	<span>
		<i class="fas fa-align-justify"></i>
	</span>
</section>

<section class="layer-logo">
	<!-- <label>SKBerge</label> -->
	<div class="logo-img"></div>
</section>

{% if request.user.is_authenticated %}
	<section class="layer-user">
		<span class="user-img">
			<i class="fas fa-user"></i>
		</span>
		<span class="user-info">
			<label>
				<b>Usuario</b> : {{user.get_full_name}}
			</label>
			<label>
				<b>Ult. acceso</b> : {{user.last_login | date:"d/m/Y h:m:s"}}
			</label>
			<label class="info-session">
				<b>Tiempo Sesión</b> : 
			</label>
			<input type="hidden" 
				name="h_deadline"
				id="h_deadline"
				value="{{expiration.date| date:"m/d/Y H:i:s"}}" >
			<input type="hidden" 
				name="h_minimun"
				id="h_minimun"
				value="{{minimun}}" >
		</span>
		{% comment %}

		{% endcomment %}
	</section>
	<section class="layer-user-details">
		<nav>
			<ul>
				<li>
					<a href="{% url 'login:additional_information' %}">
						<i class="fas fa-book-open"></i>
						Informaci&oacuten adicional
					</a>
				</li>
				<li>
					<a href="{% url 'login:change_password' %}">
						<i class="fas fa-lock"></i>
						Cambio de Clave
					</a>
				</li>
				<li>
					<a href="{% url 'login:logout' %}">
						<i class="fas fa-sign-out-alt"></i>
						Cerrar Sesi&oacuten
					</a>
				</li>
			</ul>
		</nav>
	</section>
{% else %}
	<section class="layer-user">
		<label class="user-guess">
			<b>
				<a href="{% url 'login:main' %}">Login</a>
			</b>
		</label>
	</section>
{% endif %}

intranet/templates/main/main_nav.html
<nav>
	<ul class="layer-menu">
	{% if menu %}
		{% for item in menu %}
			<li>
				<a href="#" title="{{item.descripcion}}">
					<i class="{{item.icon_class}}"></i>
					<label>{{item.descripcion}}</label>
					<i id="sort-down" class="fas fa-sort-down"></i>
					<i id="sort-up" class="fas fa-sort-up"></i>
				</a>
				{% if item.detalles %}
				<ul class="layer-menu-child">
					{% for child in item.detalles %}
					<li>
						<a  href="{% url child.view_name %}" 
							title="{{child.descripcion}}" >
							<i class="fas fa-caret-right"></i>
							<label>{{child.descripcion}}</label>
						</a>
					</li>
					{% endfor %}
				</ul>
				{% endif %}
			</li>
		{% endfor %}
	{% else %}
		<li>
			<a href="#">
				<i class="fas fa-globe"></i>
				<label>Home</label>
				<i id="sort-down" class="fas fa-sort-down"></i>
				<i id="sort-up" class="fas fa-sort-up"></i>
			</a>
		</li>
	{% endif %}
	</ul>
</nav>
<a href="#" 
	class="collapse-menu"
	title="Ocultar navegador">
	<i id="angle-left" class="fas fa-angle-double-left"></i>
	<i id="angle-right" class="fas fa-angle-double-right"></i>
	<label>
		Ocultar navegador
	</label>
</a>

intranet/templates/main/main_session.html
<div class="session-container">
	<article class="session-body">
		<h3>
			Expiración de sesión
		</h3>
		<p>
			La sesión se concluirá en <label>10 segundos</label>!
		</p>
		<footer>
			<form action="{% url 'login:logout' %}" method="GET">
				<button class="btn btn-primary" type="button">
					Extender mi sesión
				</button>
				<input class="btn btn-danger" 
					type="submit" value="Cerrar sesión" />
			</form>
		</footer>
	</article>	
</div>