intranet/apps/login/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from apps.login import views as v
app_name = 'module_login'

urlpatterns = [
    url(r'^$', v.LoginView.as_view(), name='main'),
    url(r'^refresh/$', v.RefreshView.as_view(), name='refresh'),
    url(r'^logout/$', v.LogoutView.as_view(), name='logout'),
    url(r'^validation/$', v.LoginValidation.as_view(), name='validation'),
    url(r'^change_password/$', v.LoginChangePasswd.as_view(),
        name='change_password'),
    url(r'^additional_information/$', v.LoginAdditionalInfo.as_view(),
        name='additional_information'),
    url(r'^forbidden/$', v.LoginForbidden.as_view(),
        name='forbidden'),
    url(r'^reset_password/(?P<hashid>[a-zA-Z\d]{11})/$',
        v.LoginResetPasswd.as_view(),
        name='reset_password_hash'),
    url(r'^reset_password/$', v.LoginResetPasswd.as_view(),
        name='reset_password'),
    url(r'^update_password/(?P<typeid>[a-zA-Z]{1,10})/?$',
        v.LoginExpirationPassword.as_view(),
        name='update_password_process_type'),
    url(r'^update_password/$', v.LoginExpirationPassword.as_view(),
        name='update_password'),
]

intranet/intranet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from intranet import views as v

handler404 = 'intranet.views.handler404'
handler500 = 'intranet.views.handler500'

urlpatterns = [
    url(r'^admin/?', admin.site.urls),
    url(r'^login/', include('apps.login.urls', namespace='login'),),
    url(r'^main/', include('apps.main.urls', namespace='main'),),
    url(r'^api/v1/', include('apps.api.urls', namespace='apiv1'),),
    url(r'^metas/', include('apps.metas.urls', namespace='metas'),),
    url(r'^mail/', include('apps.mail.urls', namespace='mail'),),
    url(r'^reservas/', include('apps.reservas.urls', namespace='reservas'),),
    url(r'^nofound/', v.handler404, name="nofound"),
    url(r'^grants/', include('apps.grants.urls', namespace='grants'),),
    url(r'^$', RedirectView.as_view(url='login/', permanent=False)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

intranet/apps/login/models.py
from django.db import models
from apps.common.models import CommonStructure

# Create your models here.
DEFAULT_STATUS = 1


class ClaveHistoricos(CommonStructure):
    old_password = models.CharField(max_length=128, null=False, blank=False,)
    new_password = models.CharField(max_length=128, null=False, blank=False,)

    class Meta:
        verbose_name = "Historico Claves"
        get_latest_by = ["-fhregistro", ]
        ordering = ["-fhregistro", ]
        indexes = [
            models.Index(fields=['fhregistro'],),
        ]

    def __str__(self):
        return str(self.pk)


class Bloqueos(CommonStructure):
    ultima_fecha_login = models.DateTimeField(null=False,  blank=False)

    class Meta:
        verbose_name = "Bloqueos Usuarios"
        get_latest_by = ["-fhregistro", ]
        ordering = ["-fhregistro", ]
        indexes = [
            models.Index(fields=['fhregistro'],),
            models.Index(fields=['ultima_fecha_login'],),
        ]

    def __str__(self):
        return str(self.pk)


class Accesos(CommonStructure):

    type = models.CharField(max_length=25, null=False, blank=False,)
    user_agent = models.TextField(null=True, blank=True, default=None,)
    host_from = models.CharField(
        max_length=25, null=True, blank=True, default=None)
    referer = models.TextField(null=True, blank=True, default=None,)
    url = models.CharField(max_length=200, null=True, blank=True, default=None)
    content_type = models.CharField(
        max_length=100, null=True, blank=True, default=None,)
    method = models.CharField(max_length=25, null=True,
                              blank=True, default=None)

    class Meta:
        verbose_name = "Accesos Login"
        get_latest_by = ["-fhregistro", ]
        ordering = ["-fhregistro", ]
        indexes = [
            models.Index(fields=['fhregistro'],),
            models.Index(fields=['url'],),
            models.Index(fields=['type'],),
            models.Index(fields=['method'],),
        ]

    def __str__(self):
        return '{} | {}'.format(str(self.pk), self.url)


class Intentos(CommonStructure):

    type = models.CharField(max_length=25, null=False, blank=False,)
    user_agent = models.TextField(null=True, blank=True, default=None,)
    host_from = models.CharField(
        max_length=25, null=True, blank=True, default=None)
    referer = models.TextField(null=True, blank=True, default=None,)
    url = models.CharField(max_length=200, null=True, blank=True, default=None)
    content_type = models.CharField(
        max_length=100, null=True, blank=True, default=None,)
    method = models.CharField(max_length=25, null=True,
                              blank=True, default=None)
    userid = models.CharField(max_length=25, null=True,
                              blank=True, default=None)
    username = None

    class Meta:
        verbose_name = "Intentos Login"
        get_latest_by = ["-fhregistro", ]
        ordering = ["-fhregistro", ]
        indexes = [
            models.Index(fields=['fhregistro'],),
            models.Index(fields=['url'],),
            models.Index(fields=['type'],),
            models.Index(fields=['method'],),
            models.Index(fields=['userid'],),
        ]

    def __str__(self):
        return '{} | {}'.format(str(self.pk), self.url)

    @property
    def username(self):
        raise AttributeError("'Manager' object has no attribute 'username'")


class Seguridad(CommonStructure):
    parametro = models.CharField(max_length=35, null=False, blank=False,)
    descripcion = models.CharField(max_length=100, null=False, blank=False,)
    valor = models.PositiveIntegerField(null=False, blank=False,
                                        default=0,)
    valor_default = models.PositiveIntegerField(null=True, blank=False,
                                                default=0,)
    estado = models.ForeignKey(
        'metas.Estados', on_delete=models.SET_NULL,
        null=True, default=DEFAULT_STATUS)

    class Meta:
        verbose_name = "Login Seguridad"
        get_latest_by = ["-fhregistro", ]
        ordering = ["-fhregistro", ]
        indexes = [
            models.Index(fields=['descripcion'],),
            models.Index(fields=['parametro'],),
            models.Index(fields=['fhregistro'],),
        ]

    def __str__(self):
        return str('{} | {}'.format(self.parametro, self.descripcion))

intranet/apps/login/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import (
    User,
)
from django.db.models import (
    Q, F,
)
from django.views import View
from django.urls import reverse
from rest_framework.response import Response
from django.http import (
    JsonResponse, Http404,
)
from django.conf import settings
from time import sleep
import os
import json

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import (
    login_required,
)
from apps.login import (
    serializers as srlog,
    forms as frm,
    utils as utl,
)
from apps.common.utils import Validators
from datetime import datetime

# Create your views here.

DEFAULT_MAIN_PAGE = '/main/'
if settings.DEBUG == False:
    DEFAULT_MAIN_PAGE = os.path.join(settings.PREFIX_URL, 'main')


@method_decorator(login_required, name='dispatch')
class RefreshView(View):
    defaultResponse = {
        "ok": 1,
        "status": 200,
        "result": "Request has been processed successfuly.",
    }

    def dispatch(self, *args, **kwargs):
        return super(RefreshView, self).dispatch(*args, **kwargs)

    def post(self, request):
        try:
            DATE_FORMAT = "%m/%d/%Y %H:%M:%S"
            wresponse = self.defaultResponse.copy()
            request.session.set_expiry(settings.SESSION_COOKIE_AGE)
            wexpiration = {
                "date": request.session.get_expiry_date().strftime(
                    DATE_FORMAT),
            }
            wresponse["result"] = wexpiration

        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
        return JsonResponse(wresponse, status=wresponse.get("status"))


class LogoutView(View):

    def get(self, request):
        user = request.user if request.user else None
        auth.logout(request)
        # saving user logs
        status, error = utl.saveUserLogs(user, request, utl.LOG_OUT)
        if error:
            raise ValueError(error)
        # -----------------------
        return redirect(DEFAULT_MAIN_PAGE)


class LoginForbidden(View):
    template_name = 'login/forbidden.html'
    template_header = 'SKBerge | 403 Acceso no autorizado'
    template_title = 'Acceso no autorizado'

    def get(self, request):
        header = self.template_header
        title = self.template_title
        return render(request, self.template_name, locals())


class LoginView(View):

    template_name = 'login/login.html'
    defaultResponse = {
        "ok": 1,
        "status": 200,
        "result": "Request has been processed successfuly.",
    }

    def get(self, request):
        warguments = {}
        if request.user.is_authenticated:
            return redirect(DEFAULT_MAIN_PAGE)
        return render(request, self.template_name, **warguments)


class LoginValidation(View):

    defaultResponse = {
        "ok": 1,
        "status": 200,
        "result": "Request has been processed successfuly.",
    }

    def post(self, request):
        wresponse = self.defaultResponse.copy()
        wusername = ""
        try:
            wdata = json.loads(request.body.decode("utf8"))
            wmeta = request.META.get("HTTP_REFERER")
            if not request.is_ajax():
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            status, error = self.userValidation(request)
            if error:
                raise ValueError(str(error))
            wparameters = {
                "username": wdata.get("username"),
                "password": wdata.get("passwd"),
            }
            wusername = wparameters.get("username")
            user = auth.authenticate(**wparameters)

            # validating if account is locked
            status, error = utl.checkIfUserIsLocked(wusername)
            if error:
                wresponse["status"] = 422
                raise ValueError(error)

            if user is None:
                utl.checkUserAttempsLimit(wusername)
                # 422 Unprocessable Entity
                wresponse["status"] = 422
                raise ValueError(
                    str('Credenciales no pasaron autenticación, vuelva a intentarlo.'))

            if not user.is_active:
                wresponse["status"] = 422
                raise ValueError(
                    str('Usuario no se encuentra habilitado, comunicarse con sistemas.'))

            # setting up session variables
            self.userSessionVariables(request, user)
            # create the session instance of login
            auth.login(request, user)
            # saving user logs
            status, error = utl.saveUserLogs(user, request, utl.LOG_IN)
            if error:
                raise ValueError(error)
            # -----------------------
            next_page = DEFAULT_MAIN_PAGE
            if wmeta.rfind("/?next=") > -1:
                next_page = request.build_absolute_uri(wmeta.split("=")[1])

            wresponse["result"] = {
                "message": "Autenticación fue validada satisfactoriamente.",
                "next": next_page,
            }
            return JsonResponse(wresponse, status=wresponse.get("status"))
        except Exception as e:
            wresponse['ok'] = 0
            wresponse['result'] = str(e)
            if wresponse.get('status') == 200:
                wresponse['status'] = 500
            elif wresponse.get("status") == 422:
                 # saving attemp logs
                status, error = utl.saveUserAttemps(wusername, str(e), request)
                if error:
                    print(error)
                # -----------------------
            return JsonResponse(wresponse, status=wresponse.get("status"))

    def userSessionVariables(self, request, user):
        try:
            from django.contrib.auth import models as m
            from django.db.models import Q, F, Count
            from apps.catalogos import (
                models as mdlcat, serializers as srl,
            )
            witems = m.Permission.objects.values("content_type_id") \
                .filter(Q(user=user) | Q(group__id__in=user.groups.all()) ) \
                .annotate(menusdetalle_id=F('menusdetalle'), nitems=Count('content_type_id')) \
                .order_by("content_type_id")

            wfilters = [item.get("menusdetalle_id") for item in witems]
            wmenus = mdlcat.MenusParent.objects.filter(detalles__id__in=wfilters) \
                .annotate(nitems=Count(F('id'))) \
                .prefetch_related("estado") \
                .order_by("orden")

            wsrlmenus = []
            for menu in wmenus:
                wsrl = srl.MenusParentSerializer(menu).data
                wchilds = menu.detalles.filter(
                    id__in=wfilters, estado_id=1,
                ).prefetch_related("estado")
                wsrl["detalles"] = srl.MenusDetalleSerializer(
                    wchilds, many=True,).data
                wsrlmenus.append(wsrl)

            request.session["menu"] = wsrlmenus
            request.session["username"] = user.username
            return
        except Exception as e:
            wmessage = str(e)
            print(wmessage)
            raise ValueError(wmessage)

    def userValidation(self, request):
        wstatus, werror = True, None
        try:
            wdata = json.loads(request.body.decode("utf8"))
            if not wdata.get("username"):
                wresponse['status'] = 400
                raise ValueError(
                    str('Error, Usuario de autenticación no ha sido ingresado.'))
            if not wdata.get("passwd"):
                wresponse['status'] = 400
                raise ValueError(
                    str('Error, Clave de acceso no ha sido ingresado.'))
        except Exception as e:
            wstatus = False
            werror = str(e)
        return [wstatus, werror]


@method_decorator(login_required, name='dispatch')
class LoginChangePasswd(View):

    template_name = 'login/change_password.html'
    template_header = 'SKBerge | Cambio de Clave'
    template_title = 'Cambio de Clave'

    defaultResponse = {
        "ok": 1,
        "status": 200,
        "result": "Request has been processed successfuly.",
    }

    def dispatch(self, *args, **kwargs):
        return super(LoginChangePasswd, self).dispatch(*args, **kwargs)

    def get(self, request):
        header = self.template_header
        title = self.template_title
        PWDLENGTH_FLAG = utl.getSecurityParameter("PARAM_PWDLENGTH_FLAG")
        # check if validation is enable
        if PWDLENGTH_FLAG != 0:
            password_length = utl.getSecurityParameter("PARAM_PASSWORD_LENGTH")
        return render(request, self.template_name, locals())

    def post(self, request):
        wresponse = self.defaultResponse.copy()
        try:
            wdata = json.loads(request.body.decode("utf8"))
            if not request.is_ajax():
                wresponse['status'] = 400
                raise ValueError(str('Bad Request'))
            if not request.user.is_authenticated:
                wresponse['status'] = 400
                raise ValueError(str('User no esta autenticado.'))
            status, error = self.changePasswordValidation(request)
            if error:
                raise ValueError(str(error))
            wexistence = User.objects.filter(
                username__exact=request.user.username).exists()
            if not wexistence:
                wresponse['status'] = 400
                raise ValueError(str('Usuario no existe.'))

            wuser = User.objects.get(username__exact=request.user.username)
            wpasswd_old = wuser.password
            utl.updateUserPassword(
                wuser.username, wdata.get("new_password")
            )
            wresponse[

intranet/templates/login/additional_information.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	 <link rel="stylesheet" href="{% static '/js/unpkg.com/element-ui@2.4.2/lib/theme-chalk/index.css' %}">
	 <link rel="stylesheet" href="{% static '/css/login/login_additional.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerData" id="vContainer">
		<template>
			<form>
				<div class="layerFields">
					<div class="row">
						<div class="col-12 col-sm-12 col-md-6 col-lg-4">
							<div class="form-group">
								<label class="form-label">Nombres:</label>	
								<input class="form-control" 
								type="text" 
								name="firstname"
								autocomplete="off"
								v-model="firstname"
								@blur="handleBlur">
								<div v-if="hasError('firstname')"
							    	class="alert alert-danger" 
							    	role="alert">
							    	Completar el campo
							    </div>
							</div>
						</div>
						<div class="col-12 col-sm-12 col-md-6 col-lg-4">
							<div class="form-group">
								<label class="form-label">Apellidos:</label>	
								<input class="form-control" 
								type="text" 
								name="lastname"
								autocomplete="off"
								v-model="lastname"
								@blur="handleBlur">
								<div v-if="hasError('lastname')"
							    	class="alert alert-danger" 
							    	role="alert">
							    	Completar el campo
							    </div>
							</div>
						</div>
						<div class="col-12 col-sm-12 col-md-6 col-lg-4">
							<div class="form-group">
								<label class="form-label">Email:</label>	
								<input 
								class="form-control" 
								type="email" 
								name="email"
								v-model="email"
								autocomplete="off"
								@blur="handleBlur">
								<div v-if="hasError('email')"
							    	class="alert alert-danger" 
							    	role="alert">
							    	Completar el campo
							    </div>
							</div>
						</div>
						<div class="col-12 col-sm-12 col-md-12 col-lg-12">
							<div class="form-group">
								<label class="form-label">Clave de confirmaci&oacuten:</label>	
								<input 
								class="form-control" 
								type="password" 
								name="passwd"
								v-model="passwd"
								autocomplete="current-password"
								@blur="handleBlur">
								<div v-if="hasError('passwd')"
							    	class="alert alert-danger" 
							    	role="alert">
							    	Completar el campo
							    </div>
							</div>
						</div>
					</div>
				</div>
				<div class="layerButtons">
					<div class="row">
						<div class="form-row">
							<div class="col-12 col-sm-6 col-md-4 col-lg-2">
								<button class="btn btn-success btn-block" 
									@click.prevent="handleUpdateInformation"
									:disabled="handleDisabled">
									<i class="far fa-save"></i>
									Guardar Cambios
								</button>
							</div>
							<div class="col-12 col-sm-6 col-md-4 col-lg-2" v-if="loading">
								<img src="{% static 'images/img_loader.gif' %}">
							</div>
						</div>

					</div>
				</div>
			</form>
		</template>
	</div>

{% endblock %}

{% block additionaljs %}
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/index.js' %}"></script>
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/umd/locale/es.js' %}"></script>
	<script type="text/javascript">
		ELEMENT.locale(ELEMENT.lang.es)
		axios.defaults.headers.common = {
		    'X-Requested-With': 'XMLHttpRequest',
		    'X-CSRFToken' : document.getElementsByName("csrfmiddlewaretoken")[0].value,
		};
		const axiosPostHeaders = {
			'Content-Type': 'application/x-www-form-urlencoded',
		} ;
		const URI_HOME = window.location.pathname ;
		{% if request.user %}
			const udefault = {{request.user.id}};
		{%else%}
			const udefault = null;
		{%endif%}
	</script>
	<script src="{% static '/js/login_additional.js' %}"></script>
{% endblock %}

intranet/templates/login/change_password.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	 <link rel="stylesheet" href="{% static '/js/unpkg.com/element-ui@2.4.2/lib/theme-chalk/index.css' %}">
	 <link rel="stylesheet" href="{% static '/css/login/login_passwd.css' %}">
{% endblock %}

{% block container %}
	<div class="layerTitle">
		<h3>Modulo {{title}} </h3>
	</div>
	<div class="layerData" id="vContainer">
		<form>
			<div class="layerFields">
				<div class="row">
					<div class="col-12 col-sm-12 col-md-6 col-lg-6">
						<div class="form-group">
							<label class="form-label">Clave Actual:</label>	
							<input class="form-control" 
							type="password" 
							name="passwd"
							autocomplete="current-password"
							v-model="passwd"
							@blur="handleBlur">
							<div v-if="hasError('passwd')"
						    	class="alert alert-danger" 
						    	role="alert">
						    	Completar el campo
						    </div>
						</div>
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-6">
						<div class="form-group">
							<label class="form-label">Nueva Clave:</label>	
							<input class="form-control" type="password" name="new_passwd"
							autocomplete="new-password"
							v-model="new_passwd"
							@blur="handleBlur">
							<div v-if="hasError('new_passwd')"
						    	class="alert alert-danger" 
						    	role="alert">
						    	Completar el campo
						    </div>
						</div>
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-6">
						<div class="form-group">
							<label class="form-label">Confirmar Nueva Clave:</label>	
							<input class="form-control" type="password" name="new_passwd2"
							v-model="new_passwd2"
							autocomplete="new-password"
							@blur="handleBlur">
							<div v-if="hasError('new_passwd2')"
						    	class="alert alert-danger" 
						    	role="alert">
						    	Completar el campo
						    </div>
						</div>
					</div>
					{% if password_length %}
						<div class="col-12 col-sm-12 col-md-12 col-lg-12">
							<span class="alert alert-danger advice" role="alert">
								* Longitud m&iacutenima de caracteres : 
								{% if password_length %}
									{{password_length}}
								{% endif%}
							</span>
						</div>
					{% endif%}
				</div>
			</div>
			<div class="layerButtons">
				<div class="row">
					<div class="form-row">
						<div class="col-12 col-sm-6 col-md-4 col-lg-2">
							<button class="btn btn-success btn-block" 
								@click.prevent="handleChangePasswd"
								:disabled="handleDisabled">
								<i class="fas fa-key"></i>
								Cambiar Clave
							</button>
						</div>
						<div class="col-12 col-sm-6 col-md-4 col-lg-2" v-if="loading">
							<img src="{% static 'images/img_loader.gif' %}">
						</div>
					</div>

				</div>
			</div>
		</form>
	</div>

{% endblock %}

{% block additionaljs %}
	<script src="{% static '/js/vue/dist/vue.js' %}"></script>
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/index.js' %}"></script>
	<script src="{% static '/js/unpkg.com/element-ui@2.4.2/lib/umd/locale/es.js' %}"></script>
	<script type="text/javascript">
		ELEMENT.locale(ELEMENT.lang.es)
		axios.defaults.headers.common = {
		    'X-Requested-With': 'XMLHttpRequest',
		    'X-CSRFToken' : document.getElementsByName("csrfmiddlewaretoken")[0].value,
		};
		const axiosPostHeaders = {
			'Content-Type': 'application/x-www-form-urlencoded',
		} ;
		const URI_HOME = window.location.pathname ;
	</script>
	<script src="{% static '/js/login_passwd.js' %}"></script>
{% endblock %}

intranet/templates/login/forbidden.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}
	{{header}}
{% endblock %}

{% block additionalcss %}
	 <link rel="stylesheet" href="{% static '/css/login/login_forbidden.css' %}">
{% endblock %}

{% block container %}
	<div class="row layerHeader">
		<h2>403 {{title|upper}} </h3>
		<i class="fas fa-ban"></i>
	</div>
	<div class="row layerBody">
		<article>
			<h3>¡Acceso prohibido!</h2>
			<p>
				Usted no tiene permiso para accesar a la dirección solicitada. Existe la posibilidad de que el directorio este protegido contra lectura o que no exista la documentación requerida. 

				Por favor contacte con el webmaster en caso de que usted crea que existe un error en el servidor. 
			</p>
		</article>
	</div>
	<footer>
		<span>Copyright © 2018 SKBerge Peru. All rights reserved</span>
	</footer>
{% endblock %}

{% block additionaljs %}
	<script src="{% static '/js/login_forbidden.js' %}"></script>
{% endblock %}

intranet/templates/login/login.html
{% extends 'interface/base.html' %}
{% load static %}

{% block additionalcss%}
	<link rel="stylesheet" type="text/css" href="{% static '/css/login/login.css' %}">
{% endblock %}

{% block main %}
<section class="layer-login" id="container-user">
		<div class="login-logo">
			<div class="logo-bg"></div>
			<div class="logo-img"></div>
		</div>

		<div class="login-inputs">
			<form>
				<div class="row">
					<div class="col-md-12">
					   <div class="form-group">
						   	<label for="username">Usuario</label>
						    <input 
						    	@keyup="handleKeyup"
						    	v-model="form.username"
						    	type="text" class="form-control" 
						    	name="username" 
						    	placeholder="Enter Username" 
						    	autocomplete="off"
						    	required="true">
						    <div v-if="hasError('username')"
						    	class="alert alert-danger" 
						    	role="alert">Completar nombre de usuario</div>
					   </div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label for="passwd">Clave de Acceso</label>
							<a href="{% url 'login:reset_password' %}" 
								class="forgotPasswd"
								title="Solicitar Reseteo de Clave">
								Olvidaste tu clave?
							</a>
							<input 
								@keyup="handleKeyup"
								v-model="form.passwd"
								type="password" 
								class="form-control" 
								name="passwd" 
								placeholder="Enter Password"
								autocomplete="off"
								required="true">
							<div v-if="hasError('passwd')"
						    	class="alert alert-danger" 
						    	role="alert">Completar clave de acceso</div>
						</div>
					</div>
				</div>
				<div class="row">
					<button 
						@click.prevent="handleClick"
						class="btn btn-primary btn-log btn-block">
						Ingresar
					</button>
					<div class="login-loader" v-if="loading">
						<img src="{% static 'images/img_loader.gif' %}">
					</div>
				</div>
			</form>
		</div>
</section>
{% endblock %}
{% block additionaljs %}
	<script type="text/javascript">
		const URI_VALIDATION = "{% url 'login:validation' %}" ;
	</script>
	<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
{% endblock %}

intranet/templates/login/request_password_reset.html
{% extends 'interface/base.html' %}
{% load static %}

{% block additionalcss%}
	<link rel="stylesheet" type="text/css" href="{% static '/css/login/login_request_reset.css' %}">
{% endblock %}

{% block title %}
	{{header}}
{% endblock%}

{% block main %}
<section class="layer-login" id="container-user">
	<template>
		<div class="login-logo">
			<div class="logo-bg"></div>
			<div class="logo-img"></div>
		</div>
		<div class="login-inputs">
			{% comment %}
				<!-- 
					validation if request comes with the hash parameter to reset the forget password 
				-->
			{% endcomment %}

			{% if kwargs.hashid %}
				{% include 'login/forms/form_reset_password.html' %}
			{% else %}
				{% include 'login/forms/form_request_reset.html' %}
			{% endif %}
		</div>
	</template>
</section>
{% endblock %}
{% block additionaljs %}
	{% if kwargs.hashid %}
			<script type="text/javascript">
				const URI_LOGIN = "{% url 'login:main' %}";
			</script>
			<script type="text/javascript" src="{% static 'js/login_reset_password.js' %}"></script>		
	{% else %}
			<script type="text/javascript" src="{% static 'js/login_request_reset.js' %}"></script>		
	{% endif %}
{% endblock %}

intranet/templates/login/update_password.html
{% extends 'interface/base.html' %}
{% load static %}

{% block additionalcss%}
	<link rel="stylesheet" type="text/css" 
		href="{% static '/css/login/login_request_reset.css' %}">
	<link rel="stylesheet" type="text/css" 
		href="{% static '/css/login/login_update_passwd.css' %}">
{% endblock %}

{% block main %}
<section class="layer-login" id="container-user">
	<template>
		<div class="login-logo">
			<div class="logo-bg"></div>
			<div class="logo-img"></div>
		</div>
		<div class="login-inputs">
			{% include 'login/forms/form_update_password.html' %}
		</div>
	</template>
</section>
{% endblock %}
{% block additionaljs %}
	<script type="text/javascript" src="{% static 'js/login_update_password.js' %}"></script>
	<script type="text/javascript">
		URI_UPDATEPWD = "{% url 'login:update_password' %}save"
	</script>
{% endblock %}